site_name: vAccel
nav:
  - Home: index.md
  - Getting Started:
    - requirements.md
    - build.md
    - run.md
  - Unikernels:
    - unikernels/unikraft.md
  - k8s:
    - k8s/kata.md

theme: material 
 
features:
  - navigation.instant
  - navigation.sections
  - navigation.expand
  - toc.integrate

markdown_extensions:
  - footnotes
  - attr_list

toc:
  - permalink: true

