site_name: vAccel
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - User Guide: 
    - user_guide.md
    - building.md
    - binaries.md
    - build_run_app.md
    - vm-example.md
    - remote-example.md
    #- vaccelrt.md
    #- Plugins:
    #  - jetson.md
    #  - virtio.md
    #  - coral.md
    #- run.md
  #- kata-vaccel.md
  #- k8s:
  #  - devmapper.md
  #  - k8s/kata.md
  #- Unikernels:
  #  - unikernels/unikraft.md
  #- examples.md
  #- usecases.md
  - Framework & Language bindings:
    - language_bindings.md
    - python_bindings.md
    - tensorflow_bindings.md
    - pytorch_bindings.md
  - Developer Guide:
    - dev_guide.md
    - api.md
    - Python API: python/index.md
    - plugin.md
  - Useful Docs: 
    - misc_docs.md
    - jetson.md

theme:
  name: material
  #favicon: img/vaccel-logo.png
  logo: img/vaccel-img-logo.png
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/eye
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/eye-outline
        name: Switch to light mode

#theme:
#    name: alabaster
    #custom_dir: 
#    logo: img/vaccel-logo.png
#    palette:
#        scheme: slate
#        accent: indigo
 

#extra:
#  logo: img/vaccel-logo.png
#  logo_title: "Rocketbank logo"
#  include_toc: yes
#  sidebars:
#    - about
#    - navigation
#    - related
#    - search
#
#  extra_nav_links:
#    Fork me on GitHub: https://github.com/iamale/rock-cli

features:
  - navigation.instant
  - navigation.sections
  - navigation.expand
  - toc.integrate

markdown_extensions:
  - footnotes
  - attr_list

toc:
  - permalink: true

copyright: Copyright &copy; 2018 - 2023 Nubificus LTD

#extra_css:
#  - stylesheets/extra.css
gtags:
  - G-X2S0PFR6ZY
plugins:
  - section-index
