site_name: vAccel
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - User Guide: 
    - user_guide.md
    - building.md
    - binaries.md
    - build_run_app.md
    - vm-example.md
    - remote-example.md
    #- vaccelrt.md
    #- Plugins:
    #  - jetson.md
    #  - virtio.md
    #  - coral.md
    #- run.md
  #- kata-vaccel.md
  #- k8s:
  #  - devmapper.md
  #  - k8s/kata.md
  #- Unikernels:
  #  - unikernels/unikraft.md
  #- examples.md
  #- usecases.md
  - Developer Guide:
    - dev_guide.md
    - api.md
    - plugin.md
  - Useful Docs: 
    - misc_docs.md
    - jetson.md

theme:
  name: material
  #favicon: img/vaccel-logo.png
  logo: img/vaccel-logo.png
 
features:
  - navigation.instant
  - navigation.sections
  - navigation.expand
  - toc.integrate

markdown_extensions:
  - footnotes
  - attr_list

toc:
  - permalink: true

copyright: Copyright &copy; 2018 - 2022 Nubificus LTD

extra_css:
  - stylesheets/extra.css
gtags:
  - G-X2S0PFR6ZY
plugins:
  - section-index
