site_name: vAccel
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - User Guide:
    - vaccelrt.md
    - Plugins:
      - jetson.md
      - virtio.md
      - coral.md
    - run.md
  - kata-vaccel.md
  - k8s:
    - k8s/kata.md
  - Unikernels:
    - unikernels/unikraft.md

theme:
  name: material
  #favicon: img/vaccel-logo.png
  logo: img/vaccel-logo.png
  palette:
          #primary: light green
          #accent: deep purple
    - scheme: default
      primary: light green
      accent: light green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    # Toggle dark mode
    - scheme: slate
      primary: light green
      accent: light green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
 
features:
  - navigation.instant
  - navigation.sections
  - navigation.expand
  - toc.integrate

markdown_extensions:
  - footnotes
  - attr_list

toc:
  - permalink: true

copyright: Copyright &copy; 2018 - 2021 Nubificus LTD
